spring.application.name=ms-ficha-clinica
server.port=8001

spring.cloud.compatibility-verifier.enabled=false

# ===============================
# PERFIL ACTIVO
# ===============================
spring.profiles.active=dev

# ===============================
# ENCODING
# ===============================
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# ===============================
# TIMEZONE
# ===============================
spring.jackson.time-zone=America/Santiago

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# BASE DE DATOS - POSTGRESQL (NEON)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rednorte_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rednorte_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rednorte_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Estrategias de nombres (respeta @Column exacto)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# ===============================
# INTEGRACION - BDSISPRO
# ===============================
integration.bdsispro.url=http://localhost:8001

# FHIR server (used by services via IGenericClient)
fhir.server.url=${FHIR_SERVER_URL:http://hapi-fhir:8080/fhir}

# SWAGGER / OPENAPI
springdoc.packages-to-scan=cl.rednorte.ms_ficha_clinica.controller
springdoc.paths-to-match=/api/v1/**
# http://localhost:8083/swagger-ui/index.html
