name: CI/CD Pipeline AWS Academy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Despliegue en EC2 usando AWS Systems Manager (SSM)
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["cd /home/ubuntu/Rednorte", "git pull origin main", "cd SPS-RedNorte-Infraestructura", "docker swarm init || true", "docker-compose build", "set -a && source .env && set +a", "docker stack deploy -c docker-compose.yml rednorte_stack", "docker image prune -f"]' \
          --comment "Despliegue Swarm desde GitHub Actions"
